### ISSUE TITLE
Amethyst sharing tags with vanilla Amethyst causes compatability issues with other mods.

### ISSUE THREAD

**Issue by Dutchs** [Squidsword/OresAboveDiamonds#10]
`oresabovediamonds:amethyst` and `minecraft:amethyst_shard` share the same tag: `forge:gems/amethyst`

This can cause several issues, one being due to the items not having the same inherent "value" but due to tags being considered as equal, often this is just a minor issue up to the player to decide which to use, in crafting recipes etc.

However i ran into one issue with ProjectE where it sharing a tag with a vanilla item caused it to use the emc value for vanilla amethyst which is not something that can be worked around easily.

Would you consider changing the tag for Amethyst?, `large_amethyst` or `flawless_amethyst` seem like valid options and that could extend to the item name if that's something that makes sense to you.

**Comment by Squidsword** [comment]
Makes sense, I just changed it appreciate you bringing this up.
