### ISSUE TITLE
problem with forge 41.0.98

### ISSUE THREAD

**Issue by krjencik** [Squidsword/OresAboveDiamonds#11]
---- Minecraft Crash Report ----
// But it works on my machine.

Time: 7/15/22, 1:23 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.PlayerEvent$PlayerLoggedInEvent.getPlayer()'
	at oresAboveDiamonds.events.PlayerLoggedInEventHandler.onLoginEvent(PlayerLoggedInEventHandler.java:16) ~[oresabovediamonds-9.0.0b.jar%23165!/:9.0.0b] {re:classloading}
	at oresAboveDiamonds.events.__PlayerLoggedInEventHandler_onLoginEvent_PlayerLoggedInEvent.invoke(.dynamic) ~[oresabovediamonds-9.0.0b.jar%23165!/:9.0.0b] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%2378!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:727) ~[forge-1.19-41.0.98-universal.jar%23185!/:?] {re:classloading}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:243) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:147) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:134) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:78) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:240) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:245) ~[client-1.19-20220607.102129-srg.jar%23180!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 905077312 bytes (863 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz
	Identifier: Intel64 Family 6 Model 42 Stepping 7
	Microarchitecture: Sandy Bridge (Client)
	Frequency (GHz): 3.09
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 4
	Graphics card #0 name: AMD Radeon R7 200 Series
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 2048.00
	Graphics card #0 deviceId: 0x6613
	Graphics card #0 versionInfo: DriverVersion=27.20.1034.6
	Memory slot #0 capacity (MB): 2048.00
	Memory slot #0 clockSpeed (GHz): 1.33
	Memory slot #0 type: DDR3
	Memory slot #1 capacity (MB): 2048.00
	Memory slot #1 clockSpeed (GHz): 1.33
	Memory slot #1 type: DDR3
	Virtual memory max (MB): 10965.05
	Virtual memory used (MB): 7402.01
	Swap memory total (MB): 6912.00
	Swap memory used (MB): 663.28
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['krjencik'/155, l='ServerLevel[AutofishTest]', x=-1.50, y=85.00, z=4.50]]
	Data Packs: vanilla, mod:repurposed_structures, mod:theoneprobe (incompatible), mod:terrablender (incompatible), mod:forgeautofish (incompatible), mod:biomesoplenty (incompatible), mod:sophisticatedstorage (incompatible), mod:jei (incompatible), mod:attributefix (incompatible), mod:rottenleather (incompatible), mod:goblintraders (incompatible), mod:sophisticatedcore (incompatible), mod:minicoal, mod:curios (incompatible), mod:xaerominimap, mod:forgeendertech, mod:adfinders, mod:adlods, mod:gravestone (incompatible), mod:advancednetherite, mod:xaeroworldmap, mod:oresabovediamonds, mod:dungeonnowloading, mod:citadel, mod:doubleslabs (incompatible), mod:statues, mod:dungeoncrawl, mod:sophisticatedbackpacks (incompatible), mod:guardvillagers (incompatible), mod:globalxp, mod:charmofundying (incompatible), mod:player_companions, mod:forge, mod:appleskin, mod:aquaculture, mod:t_and_t, mod:so_many_enchants (incompatible), mod:domesticationinnovation, mod:xpbook
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19-forge-41.0.98
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.0.jar eventbus PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19-41.0.98.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19-20220607.102129-srg.jar               |Minecraft                     |minecraft                     |1.19                |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		repurposed_structures_forge-6.1.3+1.19.jar        |Repurposed Structures         |repurposed_structures         |6.1.3+1.19          |DONE      |Manifest: NOSIGNATURE
		theoneprobe-1.19-6.2.0.jar                        |The One Probe                 |theoneprobe                   |1.19-6.2.0          |DONE      |Manifest: NOSIGNATURE
		TerraBlender-forge-1.19-2.0.0.120.jar             |TerraBlender                  |terrablender                  |2.0.0.120           |DONE      |Manifest: NOSIGNATURE
		forgeautofish-5.0.2-1.19.jar                      |AutoFish for Forge            |forgeautofish                 |5.0.2               |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.19-17.0.0.143.jar                 |Biomes O' Plenty              |biomesoplenty                 |17.0.0.143          |DONE      |Manifest: NOSIGNATURE
		sophisticatedstorage-1.19-0.3.7.65.jar            |Sophisticated Storage         |sophisticatedstorage          |1.19-0.3.7.65       |DONE      |Manifest: NOSIGNATURE
		jei-1.19-forge-11.0.0.222.jar                     |Just Enough Items             |jei                           |11.0.0.222          |DONE      |Manifest: NOSIGNATURE
		AttributeFix-Forge-1.19-15.0.2.jar                |AttributeFix                  |attributefix                  |15.0.2              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		RottenLeather-1.19-1.4.jar                        |Rotten Leather                |rottenleather                 |1.4                 |DONE      |Manifest: NOSIGNATURE
		goblintraders-1.7.3-1.19.jar                      |Goblin Traders                |goblintraders                 |1.7.3               |DONE      |Manifest: NOSIGNATURE
		sophisticatedcore-1.19-0.3.9.63.jar               |Sophisticated Core            |sophisticatedcore             |1.19-0.3.9.63       |DONE      |Manifest: NOSIGNATURE
		minicoal-1.19-1.0.0.jar                           |MiniCoal                      |minicoal                      |1.19-1.0.0          |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.19-5.1.0.4.jar                     |Curios API                    |curios                        |1.19-5.1.0.4        |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.11.5_Forge_1.19.jar             |Xaero's Minimap               |xaerominimap                  |22.11.5             |DONE      |Manifest: NOSIGNATURE
		ForgeEndertech-1.19-10.0.3.0-build.0499.jar       |ForgeEndertech                |forgeendertech                |10.0.3.0            |DONE      |Manifest: NOSIGNATURE
		AdFinders-1.19-8.0.2.0-build.0499.jar             |Advanced Finders              |adfinders                     |8.0.2.0             |DONE      |Manifest: NOSIGNATURE
		AdLods-1.19-7.0.2.0-build.0499.jar                |Large Ore Deposits            |adlods                        |7.0.2.0             |DONE      |Manifest: NOSIGNATURE
		gravestone-1.19-1.0.2.jar                         |Gravestone Mod                |gravestone                    |1.19-1.0.2          |DONE      |Manifest: NOSIGNATURE
		advancednetherite-1.13.5-1.19.jar                 |Advanced Netherite            |advancednetherite             |1.13.5              |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.25.3_Forge_1.19.jar              |Xaero's World Map             |xaeroworldmap                 |1.25.3              |DONE      |Manifest: NOSIGNATURE
		oresabovediamonds-9.0.0b.jar                      |Ores Above Diamonds           |oresabovediamonds             |9.0.0b              |DONE      |Manifest: NOSIGNATURE
		dungeon-now-loading-17.1-v1.19.jar                |Dungeon Now Loading           |dungeonnowloading             |1.19-17.1           |DONE      |Manifest: NOSIGNATURE
		citadel-1.12.6-1.19.jar                           |Citadel                       |citadel                       |1.12.6              |DONE      |Manifest: NOSIGNATURE
		DoubleSlabs-1.19-6.1.0.jar                        |Double Slabs                  |doubleslabs                   |6.1.0               |DONE      |Manifest: NOSIGNATURE
		Statues-1.19-0.2.0.1.jar                          |Statues Mod                   |statues                       |0.2.0.1             |DONE      |Manifest: NOSIGNATURE
		DungeonCrawl-1.19-2.3.11.jar                      |Dungeon Crawl                 |dungeoncrawl                  |2.3.11              |DONE      |Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.19-3.17.13.628.jar       |Sophisticated Backpacks       |sophisticatedbackpacks        |1.19-3.17.13.628    |DONE      |Manifest: NOSIGNATURE
		guardvillagers-1.19-1.5.1.jar                     |Guard Villagers               |guardvillagers                |1.19-1.5.1          |DONE      |Manifest: NOSIGNATURE
		globalxp-1.19-1.10.2.jar                          |Global XP                     |globalxp                      |1.10.2              |DONE      |Manifest: NOSIGNATURE
		charmofundying-forge-6.0.0-beta.2+1.19.jar        |Charm of Undying              |charmofundying                |6.0.0-beta.2+1.19   |DONE      |Manifest: NOSIGNATURE
		player_companions_1.19-2.3.0.jar                  |Bo's Player Companions        |player_companions             |2.3.0               |DONE      |Manifest: NOSIGNATURE
		forge-1.19-41.0.98-universal.jar                  |Forge                         |forge                         |41.0.98             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |DONE      |Manifest: NOSIGNATURE
		Aquaculture-1.19-2.4.4.jar                        |Aquaculture 2                 |aquaculture                   |1.19-2.4.4          |DONE      |Manifest: NOSIGNATURE
		Towns-and-Towers-1.19-1.7.2.jar                   |Towns and Towers - Structure A|t_and_t                       |1.7                 |DONE      |Manifest: NOSIGNATURE
		so_many_enchants-1.4.2.4+(1.19).jar               |So Many Enchants!!!           |so_many_enchants              |1.4.2.4 (1.19)      |DONE      |Manifest: NOSIGNATURE
		domesticationinnovation-1.5.3-1.19.jar            |Domestication Innovation      |domesticationinnovation       |1.5.3               |DONE      |Manifest: NOSIGNATURE
		xptome-1.19-2.1.6.jar                             |XP Tome                       |xpbook                        |2.1.6               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: bb8b0c77-80de-4be3-8a6b-537e8664945a
	FML: 41.0
	Forge: net.minecraftforge:41.0.98

**Comment by krjencik** [comment]
it does this: Minecraft loads, but when i tried to create a world it crashed

**Comment by Squidsword** [comment]
fixed thanks for reporting
