### ISSUE TITLE
[1.17] Mod will not load due to Forge Change

### ISSUE THREAD

**Issue by ffuentesm** [Squidsword/OresAboveDiamonds#5]
When loading the following error appears.
java.lang.NoClassDefFOundError: net/minecraftforge/common/ToolType

The Forge version is: 37.0.33

Forge removed the ToolType API and replaced it for the serializer ToolAction system.

**Comment by Squidsword** [comment]
Reworked the system, should work for the latest version now. Thanks for the report!
