### ISSUE TITLE
Deepslate Black Opal Ore mining requirement bug

### ISSUE THREAD

**Issue by littlepianist** [Squidsword/OresAboveDiamonds#9]
Deepslate Black Opal ore can be mined with pickaxes below diamond level now
![2022-02-06_12 46 34](https://user-images.githubusercontent.com/75674050/152668360-3d211f51-b91d-4d89-91ee-0442af5c9b54.png)
w

**Comment by Squidsword** [comment]
Do you remember which version? If it's in a mod pack you can check in the mods folder on the main menu. On the latest version, I tested it and it was working fine.  Sorry for the late reply.

([relevant files](https://github.com/Squidsword/OresAboveDiamonds/blob/1.18.1/src/main/resources/data/oresabovediamonds/tags/blocks/needs_amethyst_tool.json))
